name: CI/CD-HeroVired



on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    env: 
      MONGO_URI: ${{ secrets.MONGO_TEST_URI }}    
      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      

      
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set test stage
        run: echo "FAILED_STAGE=test" >> $GITHUB_ENV


      - name: install dependencies
        run: pip install -r requirements.txt    

      - name: Run tests
        id: test
        run: |
         echo "FAILED_STAGE=test" >> $GITHUB_ENV
         pytest

      - name: Build Docker image
        id: build
        run: |
         echo "FAILED_STAGE=build" >> $GITHUB_ENV
         docker build -t flask-practice:${{ github.sha }} .

      - name: Set push stage
        run: echo "FAILED_STAGE=push" >> $GITHUB_ENV

        
         
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image to ECR
        id: push
        env: 
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         REPOSITORY: flask-practice
         IMAGE_TAG: ${{ github.sha }}
        run: |
         echo "FAILED_STAGE=push" >> $GITHUB_ENV
         docker tag flask-practice:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Set deploy stage
        run: echo "FAILED_STAGE=deploy" >> $GITHUB_ENV

      - name: EC2-Deployment
        id: deploy
        uses: appleboy/ssh-action@v1.2.2
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            IMAGE="691317217805.dkr.ecr.ap-south-1.amazonaws.com/flask-practice:${{ github.sha }}"

            echo "ECR access"
            aws ecr get-login-password --region ap-south-1 | \
              docker login --username AWS --password-stdin \
              691317217805.dkr.ecr.ap-south-1.amazonaws.com

            echo "Getting new Image"
            docker pull $IMAGE

            echo "Stopping existing container.."
            docker stop flask-app || true

            echo "Removing existing container.."
            docker rm flask-app || true

            echo "Starting new container.."
            docker run -d \
             --name flask-app \
             --env-file /home/ubuntu/flask.env \
             -p 5000:5000 \
             $IMAGE

             echo "Waiting for application"
             sleep 10

             echo "Checking application health"
             curl --fail http://localhost:5000/health
             
      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[FAILED] CI/CD-HeroVired Deployment"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          body: |
            CI/CD deployment FAILED.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit SHA: ${{ github.sha }}

            Failed Stage : ${{ env.FAILED_STAGE }}

            Stage results:
            Test: ${{ steps.test.outcome }}
            Build: ${{ steps.build.outcome }}
            Push: ${{ steps.push.outcome }}
            Deploy: ${{ steps.deploy.outcome }}

            Pipeline run:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send success email
        if: success()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[SUCCESS] CI/CD-HeroVired Deployment"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          body: |
            CI/CD deployment completed successfully.

            Repository: ${{ github.repository }}
            Status: SUCCESS

            Branch deployed:
            ${{ github.ref_name }}

            Git commit SHA:
            ${{ github.sha }}

            Docker image pushed to ECR:
            691317217805.dkr.ecr.ap-south-1.amazonaws.com/flask-practice:${{ github.sha }}

            EC2 target:
            ${{ secrets.EC2_HOST }}

            Pipeline run:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}   
